site_name: Backstage Demo
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/bortington/backstage-test
edit_uri: edit/main/docs

plugins:
  - mermaid2
  
nav:
  - Getting Started:
    - getting-started.md
    - techdocs.md
    - auth.md
  - Deployment:
    - deployment.md
  - Samples:
    - mermaid-diagrams.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
