site_name: Backstage Demo
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/bortington/backstage-test
edit_uri: edit/main/docs

plugins:
  - mermaid2

theme:
  name: material
  
nav:
  - Getting Started:
    - getting-started.md
    - techdocs.md
    - auth.md
    - techdocs.md
  - Deployment:
    - deployment.md
  - Samples:
    - mermaid-diagrams.md
  - Resources: resources.md
