site_name: Backstage Demo
docs_dir: docs

nav:
  - Getting Started:
    - getting-started.md
    - techdocs.md
    - auth.md
  - Deployment:
    - deployment.md
  - Samples:
    - mermaid-diagrams.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format