name: build

on:
  push:
    branches:
      - main
    paths:
      - 'backstage/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build backstage -t fredstage
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker tag fredstage bortos/fredstage
      - run: docker push bortos/fredstage:latest